name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build with Maven
        run: gradle clean build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Deploy
        run: |
          echo "Deploying artifact to staging..."
          ls target/*.jar
